#!/usr/bin/env bash
# install nginx
sudo apt -y update
sudo apt -y install nginx
#allow uncomplicated firewall for HTTP
sudo ufw allow 'Nginx HTTP'
#configration begins here

#default page 
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo tee  /etc/nginx/sites-a*/default<<EOF
server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.html;
    location / {
        index.html
    }
}
EOF
sudo service nginx start
