#!/usr/bin/env bash
# 301 redirection set up
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Ngix HTTP'
echo "Hello World!" | sudo tee /etc/nginx/html/index.html
sudo tee /etc/nginx/sites-available/default << EOF
server {
    listen 80;
    location /redirect_me {
        return 301 http://https://www.youtube.com/watch?v=QH2-TGUlwu4
        }
}
EOF
sudo system start nginx
