#!/usr/bin/env bash
#congures an Ubuntu server as following 
#	-localhost resolve to 127.0.0.2
#	-facebook.com resolve to 8.8.8.8

cp /etc/hosts ~/hosts.newconfig
echo "127.0.0.2		localhost" > ~/hosts.newconfig
echo "8.8.8.8		facebook.com" >> ~/hosts.newconfig
cp -f ~/hosts.newconfig /etc/hosts
