#!/usr/bin/env bash                                                                                                              
# Run Apache on the holbertonschool/265-0 Docker container.                                                                      
echo "apache2 is running" >> /etc/apache2.conf                                                                                 
service apache2 start